# Generated by Django 6.0.3 on 2026-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Target Opportunity"),
                ),
                (
                    "asset_class",
                    models.CharField(max_length=100, verbose_name="Asset Class"),
                ),
                (
                    "region",
                    models.CharField(max_length=150, verbose_name="Geographic Node"),
                ),
                (
                    "g_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Geopolitical Score (G)"
                    ),
                ),
                (
                    "e_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Economic Score (E)"
                    ),
                ),
                (
                    "v_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Valuation Score (V)"
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Final O Score"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action (Tier 1)"),
                            ("SUPPRESS", "Suppress (OFAC)"),
                            ("MONITOR", "Monitor"),
                        ],
                        default="MONITOR",
                        max_length=20,
                        verbose_name="Investment Status",
                    ),
                ),
            ],
        ),
    ]
