# Generated by Django 6.0.3 on 2026-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator_name",
                    models.CharField(max_length=150, verbose_name="Specific Indicator"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEOPOLITICAL", "Geopolitical"),
                            ("COMMODITY", "Commodity"),
                            ("FIXED_INCOME", "Fixed Income"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_value", models.FloatField(verbose_name="Current Value")),
                (
                    "unit",
                    models.CharField(
                        help_text="e.g., /bbl, /lb, %, bps", max_length=20
                    ),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ingestion Timestamp"
                    ),
                ),
                (
                    "half_life_days",
                    models.IntegerField(
                        blank=True,
                        help_text="7 for Geopolitical, 14 for Commodity, Null for Fixed Income",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
